#coding=utf-8
guest_name=['Les Miserables', 'Hobbit', 'Monsters University', 'Seabiscuit']
print("Hello " + guest_name[0] + ", "  + "I hope that you can join my feast!")
print("Hello " + guest_name[1] + ", "  + "I hope that you can join my feast!")
print("Hello " + guest_name[2] + ", "  + "I hope that you can join my feast!")
print("Hello " + guest_name[3] + ", "  + "I hope that you can join my feast!")
absent_guest = guest_name.pop(0)
print(absent_guest.title() +"  can't to be here in that time.")
guest_name.append('Bestman')
print("Hello " + guest_name[0] + ", "  + "I hope that you can join my feast!")
print("Hello " + guest_name[1] + ", "  + "I hope that you can join my feast!")
print("Hello " + guest_name[2] + ", "  + "I hope that you can join my feast!")
print("Hello " + guest_name[3] + ", "  + "I hope that you can join my feast!")
print("Hello Guests, We find a new place to play ")
guest_name.append('Wonder')
print(guest_name)
guest_name.insert(0,'Pocahontas')
guest_name.insert(0,'Single Man')
print(guest_name)
